# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-26 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(verbose_name=b'Start Date')),
                ('enrollment_start_date', models.DateTimeField(verbose_name=b'Enrollment Start Date')),
                ('enrollment_end_date', models.DateTimeField(verbose_name=b'EnrollmentStart Date')),
                ('studio_version', models.BooleanField(default=False, verbose_name=b'Course shift related to studio settings')),
                ('enabled', models.BooleanField(default=False, verbose_name=b'Course shifts are enabled for course')),
            ],
            options={
                'db_table': 'course_shifts',
            },
        ),
        migrations.CreateModel(
            name='CourseShiftUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('course_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_shifts.CourseShift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_shift_user',
            },
        ),
        migrations.AlterUniqueTogether(
            name='courseshiftuser',
            unique_together=set([('user', 'course_key')]),
        ),
    ]
