# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseshift',
            name='studio_version',
            field=models.BooleanField(default=False, verbose_name=b'Course shift related to studio settings'),
        ),
    ]
